repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff-format
        args: ["-C", "./backend"]
      - id: ruff
        args: [--fix]
        args: ["-C", "./backend"]
